### Create a new user

POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "full_name" : "Sharon Birgen",
    "email": "sharoncherotich112@gmail.com",
    "password": "Boomplay@1"
}

### Login a user

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "kennynet66@gmail.com",
    "password": "Boomplay@1"
}

### Get all users

GET http://localhost:5000/users

### Get a single user by ID

GET http://localhost:5000/users/3e2ea21f-c6f5-4b9f-9948-b387d7338dee

### Delete user by ID

DELETE http://localhost:5000/users/delete/93a34ede-c1fd-43d9-af16-754d42e35a7d

### Create a new project
POST http://localhost:5000/project/newproject
Content-Type: application/json

{
    "project_name": "Create Fullstack",
    "project_description": "This is a description",
    "assigned_to":"Kenedy Maina",
    "end_date": "14/02/24",
    "asignee_name": "Kenedy Maina"
}

### Get all projects
GET http://localhost:5000/project

### Delete Project by ID

POST http://localhost:5000/project/delete/ce0f045b-f33f-4a40-b3d4-597a12740d30